version: '3.3'
services:
  db:
    image: postgis/postgis:16-master
    restart: always
    environment:
      - POSTGRES_DB=blogo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'